import type { ReleaseWorkflowBlueprint } from "../types.js";

/**
 * Versioned data blueprint reconstructed from the completed beta.80 sequence.
 * It describes allowlisted actions and gates only; it contains no commands,
 * credentials, release target, or production adapter.
 */
export const beta80ReleaseBlueprint: ReleaseWorkflowBlueprint = {
  id: "mcp-v3-public-release",
  version: 1,
  name: "MCP V3 signed public release, sequential deployment and homologation",
  historicalReference: "v1.1.0-beta.80",
  stages: ["build_release", "deployment", "homologation"],
  gates: [
    {
      id: "signed_release_validated",
      stage: "build_release",
      requiredEvidenceKinds: ["canonical_ci_run", "signed_manifest", "release_asset_digest"],
    },
    {
      id: "edge_healthy",
      stage: "deployment",
      requiredEvidenceKinds: ["edge_health_report"],
    },
    {
      id: "oracle_healthy",
      stage: "deployment",
      requiredEvidenceKinds: ["oracle_active_manifest", "oracle_health_report"],
    },
    {
      id: "windows_healthy",
      stage: "deployment",
      requiredEvidenceKinds: ["windows_active_manifest", "windows_health_report"],
    },
  ],
  steps: [
    {
      id: "resolve_main_commit",
      stage: "build_release",
      action: "resolve_main_commit",
      executionClass: "read_only",
      dependsOn: [],
      requiredGates: [],
    },
    {
      id: "verify_canonical_ci",
      stage: "build_release",
      action: "verify_canonical_ci",
      executionClass: "read_only",
      dependsOn: ["resolve_main_commit"],
      requiredGates: [],
    },
    {
      id: "publish_release_tag",
      stage: "build_release",
      action: "publish_release_tag",
      executionClass: "external_effect",
      dependsOn: ["verify_canonical_ci"],
      requiredGates: [],
    },
    {
      id: "build_and_sign_release",
      stage: "build_release",
      action: "build_and_sign_release",
      executionClass: "external_effect",
      dependsOn: ["publish_release_tag"],
      requiredGates: [],
    },
    {
      id: "publish_signed_release",
      stage: "build_release",
      action: "publish_signed_release",
      executionClass: "external_effect",
      dependsOn: ["build_and_sign_release"],
      requiredGates: [],
    },
    {
      id: "verify_release_assets",
      stage: "build_release",
      action: "verify_release_assets",
      executionClass: "read_only",
      dependsOn: ["publish_signed_release"],
      requiredGates: [],
      healthGateId: "signed_release_validated",
    },
    {
      id: "deploy_edge",
      stage: "deployment",
      action: "deploy_edge",
      executionClass: "external_effect",
      dependsOn: ["verify_release_assets"],
      requiredGates: ["signed_release_validated"],
    },
    {
      id: "verify_edge_health",
      stage: "deployment",
      action: "verify_edge_health",
      executionClass: "read_only",
      dependsOn: ["deploy_edge"],
      requiredGates: [],
      healthGateId: "edge_healthy",
    },
    {
      id: "prepare_oracle",
      stage: "deployment",
      action: "prepare_oracle",
      executionClass: "external_effect",
      dependsOn: ["verify_edge_health"],
      requiredGates: ["edge_healthy"],
    },
    {
      id: "prepare_windows",
      stage: "deployment",
      action: "prepare_windows",
      executionClass: "external_effect",
      dependsOn: ["verify_edge_health"],
      requiredGates: ["edge_healthy"],
    },
    {
      id: "validate_oracle_candidate",
      stage: "deployment",
      action: "validate_oracle_candidate",
      executionClass: "read_only",
      dependsOn: ["prepare_oracle"],
      requiredGates: [],
    },
    {
      id: "validate_windows_candidate",
      stage: "deployment",
      action: "validate_windows_candidate",
      executionClass: "read_only",
      dependsOn: ["prepare_windows"],
      requiredGates: [],
    },
    {
      id: "promote_oracle",
      stage: "deployment",
      action: "promote_oracle",
      executionClass: "external_effect",
      dependsOn: ["validate_oracle_candidate", "validate_windows_candidate"],
      requiredGates: ["signed_release_validated", "edge_healthy"],
    },
    {
      id: "verify_oracle_health",
      stage: "deployment",
      action: "verify_oracle_health",
      executionClass: "read_only",
      dependsOn: ["promote_oracle"],
      requiredGates: [],
      healthGateId: "oracle_healthy",
    },
    {
      id: "promote_windows",
      stage: "deployment",
      action: "promote_windows",
      executionClass: "external_effect",
      dependsOn: ["validate_windows_candidate", "verify_oracle_health"],
      requiredGates: ["oracle_healthy"],
    },
    {
      id: "verify_windows_health",
      stage: "deployment",
      action: "verify_windows_health",
      executionClass: "read_only",
      dependsOn: ["promote_windows"],
      requiredGates: [],
      healthGateId: "windows_healthy",
    },
    {
      id: "reconcile_final_pointers",
      stage: "homologation",
      action: "reconcile_final_pointers",
      executionClass: "read_only",
      dependsOn: ["verify_windows_health"],
      requiredGates: ["oracle_healthy", "windows_healthy"],
    },
    {
      id: "smoke_catalog",
      stage: "homologation",
      action: "smoke_catalog",
      executionClass: "read_only",
      dependsOn: ["reconcile_final_pointers"],
      requiredGates: [],
    },
    {
      id: "cleanup_known_temporary_residue",
      stage: "homologation",
      action: "cleanup_known_temporary_residue",
      executionClass: "external_effect",
      dependsOn: ["smoke_catalog"],
      requiredGates: [],
    },
  ],
};
